
document.getElementById('subject-title').innerText = 'CIVIL SERVICE PRACTICE EXAM';
document.getElementById('sidebar-subject-title').innerText = 'CIVIL SERVICE PRACTICE EXAM';

const cse_topics = {
    0 : 'ALL',
    1 : 'MATHEMATICS',
    //2 : 'VERBAL ABILITY',
    //2.1 : 'Word Meaning',
    2.2 : 'Sentence Completion',
    2.3 : 'Antonyms',
    //3 : 'FILIPINO',
    4 : 'PHILIPPINE CONSTITUTION',
    //5 : 'INDUCTIVE REASONING',
    //6 : 'ABSTRACT REASONING',
    //7 : 'LOGICAL REASONING'
}

const sideBarContainer = document.getElementById("topicLinks"); // The container where links will be inserted

Object.entries(cse_topics).forEach(([key, value]) => {
  const a = document.createElement("a");
  a.href = `../library/practiceExam.html?page=1&subject=cse_question&topic=${key}`;
  a.id = `topic-${key}`;
  a.className = `w3-bar-item w3-button w3-padding `;
  a.innerHTML = `<img src="" class="notepadIcon">${value}`;
  sideBarContainer.appendChild(a);
});


const practiceTest = document.createElement("a");
practiceTest.href = `../library/quiz.html?page=1&subject=cse_question&topic=`;
practiceTest.className = `w3-bar-item w3-button w3-padding topic-quiz`;
practiceTest.innerHTML = `<img src="" class="notepadIcon">PRACTICE QUIZ (FLASHCARD)`;
sideBarContainer.appendChild(practiceTest);



const questions = [
    {
        no : 1, 
        topic: 1,
        type : 'M',
        question : 'Find the sum: 299 + 943 + 398 + 101.',
        choices : {
            a : '1 531',
            b : '1 641',
            c : '1 741',
            d : '122 222',
        },
        answer : 'c',
        explanation: 'The sum of 299 + 943 + 398 + 101 is <b>1 741</b>',
    },
    {
        no : 2, 
        topic: 1,
        type : 'M',
        question : 'If 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55, then 11 + 12 + 13 + 14 + 15 + 16 + 17 + 18 + 19 + 20 = ?',
        choices : {
            a : '65',
            b : '155',
            c : '125',
            d : '550',
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : 3, 
        topic: 1,
        type : 'M',
        question : 'If 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55, then 101 + 102 + 103 + 104 + 105 + 106 + 107 + 108 + 109 + 110 = ?',
        choices : {
            a : '1 055',
            b : '1 065',
            c : '1 075',
            d : '5 500',
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : 4, 
        topic: 1,
        type : 'M',
        question : 'Evaluate: {16 - (24 - 8) + 22 x 8 - 8}.',
        choices : {
            a : '40',
            b : '48',
            c : '64',
            d : '168',
        },
        answer : 'd',
        explanation: '',
    },
    {
        no : 5, 
        topic: 1,
        type : 'M',
        question : 'If 23 + 28 + 37 + x + 53 = 168 and 23 + 28 + 40 + y + 50 = 120. Find the value of x - y?',
        choices : {
            a : '36',
            b : '48',
            c : '56',
            d : '64',
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : 6, 
        topic: 1,
        type : 'M',
        question : 'Find the product: 800 x 125',
        choices : {
            a : '925',
            b : '1 000',
            c : '10 000',
            d : '100 000',
        },
        answer : 'd',
        explanation: '',
    },
    {
        no : 7, 
        topic: 1,
        type : 'M',
        question : 'Find the quotient: 8000 / 125',
        choices : {
            a : '48',
            b : '64',
            c : '80',
            d : '88',
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : 8, 
        topic: 1,
        type : 'M',
        question : 'What is the remainder when 192 888 is divided by 8?',
        choices : {
            a : '0',
            b : '4',
            c : '8',
            d : '24 111',
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : 9, 
        topic: 1,
        type : 'M',
        question : 'Rounding 299 943 to the nearest thousands the result is',
        choices : {
            a : '299 940',
            b : '299 000',
            c : '299 900',
            d : '300 000',
        },
        answer : 'd',
        explanation: '',
    },
    {
        no : 10, 
        topic: 1,
        type : 'M',
        question : '398.101 is read as',
        choices : {
            a : 'three hundred ninety eight, one hundred one.',
            b : 'three hundred ninety eight and one hundred one.',
            c : 'three hundred ninety eight and one hundred',
            d : 'three hundred ninety eight and one hundred one thousandths',
        },
        answer : 'd',
        explanation: '',
    },
    {
        no : 11, 
        topic: 1,
        type : 'M',
        question : 'A number is divisible by 8 if its last three digit is divisible by 8. Which of the following numbers is divisible by 8?',
        choices : {
            a : '9 208',
            b : '6 236',
            c : '88 254',
            d : '8 886',
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : 12, 
        topic: 1,
        type : 'M',
        question : 'A number is divisible by 8 if its last three digit is divisible by 8. Which of the following numbers is divisible by 8?',
        choices : {
            a : '9 208',
            b : '6 236',
            c : '88 254',
            d : '8 886',
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : 4.1, 
        topic: 4,
        type : 'M',
        question : 'What is the highest law of the land in the Philippines',
        choices : {
            a : 'Civil Code',
            b : 'Philippine Constitution',
            c : 'Penal Code',
            d : 'Local Government Code',
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : 4.2, 
        topic: 4,
        type : 'M',
        question : 'How many articles are there in the 1987 Philippine Constitution?',
        choices : {
            a : '18',
            b : '12',
            c : '21',
            d : '22',
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : 4.3, 
        topic: 4,
        type : 'M',
        question : 'Which branch of the government is responsible for making laws?',
        choices : {
            a : 'Executive',
            b : 'Legislative',
            c : 'Judicial',
            d : 'Electoral',
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : 4.4, 
        topic: 4,
        type : 'M',
        question : 'The power to declare martial law is vested in which official?',
        choices : {
            a : 'Senate President',
            b : 'Chief Justice',
            c : 'President of the Philippines',
            d : 'Speaker of the House',
        },
        answer : 'c',
        explanation: '',
    },
    {
        no : 4.5, 
        topic: 4,
        type : 'M',
        question : 'Which article of the Constitution focuses on the Bill of Rights',
        choices : {
            a : 'Article II',
            b : 'Article III',
            c : 'Article IV',
            d : 'Article V',
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : 4.6, 
        topic: 4,
        type : 'M',
        question : 'Who is responsible for determining the existence of probable cause for the issuance of a warrant of arrest or search warrant?',
        choices : {
            a : 'Lawyer',
            b : 'Judge',
            c : 'Fiscal',
            d : 'Prosecutor',
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : 4.7, 
        topic: 4,
        type : 'M',
        question : 'The Senate shall be composed of how many senators elected at large by voters of the Philippines?',
        choices : {
            a : '21',
            b : '22',
            c : '23',
            d : '24',
        },
        answer : 'd',
        explanation: '',
    },
    {
        no : 4.8, 
        topic: 4,
        type : 'M',
        question : 'The term of office of the President and Vice-President of the Philippines shall be up to how many years?',
        choices : {
            a : '3 Years',
            b : '4 Years',
            c : '5 Years',
            d : '6 Years',
        },
        answer : 'd',
        explanation: '',
    },
    {
        no : 4.9, 
        topic: 4,
        type : 'M',
        question : 'It states that "no person shall be deprived of life, liberty, or property without due process of law, nor any person be denied the equal protection of the laws.',
        choices : {
            a : 'Article VI',
            b : 'Bill of Rights',
            c : 'Republic Act',
            d : 'Court Order',
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : 4.10, 
        topic: 4,
        type : 'M',
        question : 'What are the 3 branches of the Governemnt of the Philippines?',
        choices : {
            a : 'Senate, Supreme Court, Congress',
            b : 'Presidential, Unicameral - Parliamentary, Bicameral -Parliamentary',
            c : 'Legislative, Executive, Judicial',
            d : 'The Legislative, The Senate, The Supreme Court',
        },
        answer : 'c',
        explanation: '',
    },
    {
        no : 4.11, 
        topic: 4,
        type : 'M',
        question : 'The following shall be exempted from taxation except:',
        choices : {
            a : 'Lands and buildings',
            b : 'Churches and convents',
            c : 'Charitable institutions',
            d : 'Non-profit cemeteries',
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : 4.12, 
        topic: 4,
        type : 'M',
        question : 'It is a law in the Philippines that aims to address legal issues concerning online interactions and harmful internet behavior in the Philippines. It aims to present and punish cybercrime in the country.',
        choices : {
            a : 'Cybersquatting',
            b : 'Cybercrime Act',
            c : 'Cybercrime Prevention Act',
            d : 'Cyber Identity Theft Act',
        },
        answer : 'c',
        explanation: '',
    },
    {
        no : 4.13, 
        topic: 4,
        type : 'M',
        question : 'It is a project of DOST for more accurate integrated and responsive disaster prevention and mitigation system expecially in high-risk calamity areas of the Philippines',
        choices : {
            a : 'PAGASA',
            b : 'I am ready',
            c : 'DOST - Advance Disaster Program',
            d : 'Project NOAH',
        },
        answer : 'd',
        explanation: 'D. Project NOAH - Nationwide Operational Assessment of Hazards',
    },
    {
        no : 4.14, 
        topic: 4,
        type : 'M',
        question : 'The member of the House of Representatives shall be elected for a term of _____.',
        choices : {
            a : '3 Years',
            b : '4 Years',
            c : '5 Years',
            d : '6 Years',
        },
        answer : 'a',
        explanation: 'A. 3 Years is the term of the Elecetd Represenative and also the Senator',
    },
    {
        no : 4.15, 
        topic: 4,
        type : 'M',
        question : 'It is the power of the State to promote public welfare by restraining the use of both liberty and property of all people',
        choices : {
            a : 'Police Power',
            b : 'Power of Eminent Domain',
            c : 'Power of Taxation',
            d : 'Power to Impeach',
        },
        answer : 'a',
        explanation: 'A. Police Power',
    },
    {
        no: "4.2025edCSC-2",
        topic: 4,
        type: 'M',
        question: 'The legislative power shall be vested in the ______ which shall consist of a Senate and a House of Representative',
        choices: {
            a: 'Congress of the Philippines',
            b: 'House of Ombudsman',
            c: 'The Supreme Court',
            d: 'Bureau of Internal Revenuw',
        },
        answer: 'a',
        explanation: 'Legislative power is vested in the Congress of the Philippines, composed of the Senate and the House of Representatives, as stated in Article VI, Section 1 of the 1987 Philippine Constitution.',
    },
    {
        no: "4.2025edCSC-3",
        topic: 4,
        type: 'M',
        question: 'Who is the current Senate President of the Philippines?',
        choices: {
            a: 'Vicente Castelo Sotto III',
            b: 'Juan Miguel "Migz" Fernandex Zubiri',
            c: 'Francis Joseph "Chiz" Guevara Escudero',
            d: 'Frankin Magtanao Drilon',
        },
        answer: 'c',
        explanation: 'As of 2025, the current Senate President of the Philippines is Francis "Chiz" Escudero, elected to the position in 2024.',
    },
    {
        no: "4.2025edCSC-4",
        topic: 4,
        type: 'M',
        question: 'Who is the current Speaker of the House of Representative in the Philippines?',
        choices: {
            a: 'Elizaldy S. Co',
            b: 'Ferdinand Martin G. Romualdez',
            c: 'Stella Luz A. Quimbo',
            d: 'Gloria Macapagal-Arroyo',
        },
        answer: 'b',
        explanation: 'Ferdinand Martin G. Romualdez continues to serve as the Speaker of the House of Representatives as of 2025, a position he held since 2022.',
    },
    {
        no: "4.2025edCSC-5",
        topic: 4,
        type: 'M',
        question: 'Who is the current Chairperson of the House Committee on Appropriations?',
        choices: {
            a: 'Elizaldy "Zaldy" S. Co',
            b: 'Manuel Jose "Mannix" Dalipe',
            c: 'Stella Luiz A. Quimbo',
            d: 'Ferdinand Martin G. Romualdez',
        },
        answer: 'a',
        explanation: 'Elizaldy "Zaldy" Co is the current Chairperson of the House Committee on Appropriations, responsible for handling budget-related legislation in the House.',
    },
    {
        no: "4.2025edCSC-6", 
        topic: 4,
        type: 'M',
        question: 'The executive power shall be vested in the ____.',
        choices: {
            a: 'President of the Philippines',
            b: 'House of Representatives',
            c: 'The Supreme Court',
            d: 'The Congress',
        },
        answer: 'a',
        explanation: 'According to Article VII, Section 1 of the 1987 Philippine Constitution, the executive power is vested in the President of the Philippines, who acts as the head of state and government.',
    },
    {
        no : "2.R", 
        topic: 2.2,
        type : 'M',
        question : 'The researcher’s groundbreaking work was met with initial resistance, but over time, it gained widespread _______ as further studies confirmed its validity.',
        choices : {
            a : 'Disapproval',
            b : 'Recognition',
            c : 'Indifference',
            d : 'Opposition',
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : "2.R", 
        topic: 2.2,
        type : 'M',
        question : 'The engineers said the bridge was now ______, however, no one wanted to risk crossing it.',
        choices : {
            a : 'protected',
            b : 'prudent',
            c : 'fixed',
            d : 'safe',
        },
        answer : 'c',
        explanation: 'The structure of the sentence gives us a clue. It has two contrasting parts, connected by "however," which signals a contradiction. This means that although the engineers claimed something positive, people still did not trust the bridge enough to cross it. So, "fixed" makes the most sense because it acknowledges that the bridge was repaired, but people were still unsure or scared to cross—which matches the contrast introduced by “however.”',
    },
    {
        no : "2.CSC-1", 
        topic: 2.2,
        type : 'M',
        question : 'The commoners played a show about the Lannisters, a _____ of the ineffective rulling of the leaders of King\'s Landing.',
        choices : {
            a : 'Play',
            b : 'Travesty',
            c : 'Pretention',
            d : 'Role-Playing',
            e : 'Showcase'
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : "2.CSC-2", 
        topic: 2.2,
        type : 'M',
        question : 'The dentist ridiculed his patient\' ____ tooth enamel.',
        choices : {
            a : 'hard',
            b : 'favorable',
            c : 'healthy',
            d : 'mottled',
            e : 'lovely'
        },
        answer : 'd',
        explanation: '',
    },
    {
        no : "2.R", 
        topic: 2.2,
        type : 'M',
        question : 'To ensure that Nathalie wouldn\'t know where we were going for her birthday, I took the most _____ route i could think of.',
        choices : {
            a : 'circuitous',
            b : 'craven',
            c : 'enigmatic',
            d : 'mercurial',
        },
        answer : 'a',
        explanation: 'The best word to complete the sentence is a. circuitous.',
    },
    {
        no : "2.CSC-3", 
        topic: 2.2,
        type : 'M',
        question : 'Arya _____ upon witnessing his father\'s decapitation. Her face because ashen upon seeing such horabble scene, and she was not able to say anuthing for a while.',
        choices : {
            a : 'Gasped',
            b : 'Looked',
            c : 'Flummoxed',
            d : 'Breathed',
            e : 'Flunked'
        },
        answer : 'c',
        explanation: '',
    },
    {
        no : "2.CSC-4", 
        topic: 2.2,
        type : 'M',
        question : 'Emma Watson was chosen to become a/an _____ for the remake of Beauty and the Beast in 2017. She will be playing as Belle.',
        choices : {
            a : 'Antagonist',
            b : 'Protagonist',
            c : 'Wicked',
            d : 'Opponent',
            e : 'Narrator'
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : "2.CSC-5", 
        topic: 2.2,
        type : 'M',
        question : 'The beast promised to _____ havoc if ever somebody trespasses his kingdom.',
        choices : {
            a : 'Endow',
            b : 'Warrant',
            c : 'Ensue',
            d : 'Placate',
            e : 'Wreak'
        },
        answer : 'e',
        explanation: '',
    },
    {
        no : "2.CSC-6", 
        topic: 2.2,
        type : 'M',
        question : 'Mae\'s talent in singing _____ under the tutelage of Prof. Dela Cruz, her music teacher. She is now a well-known singer from across the world.',
        choices : {
            a : 'Improved',
            b : 'Flourished',
            c : 'Embellished',
            d : 'Colluded',
            e : 'touted'
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : "2.CSC-7", 
        topic: 2.2,
        type : 'M',
        question : 'Ana reached the _____ of her career upon the release of her second novel, which gained positive remarks from world-renowned authors from different countries.',
        choices : {
            a : 'Apogee',
            b : 'Plateau',
            c : 'Bottom',
            d : 'Trough',
            e : 'Downfall'
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : "2.CSC-8", 
        topic: 2.2,
        type : 'M',
        question : 'Smoking cigarettes is mostly _____ in some part of the world. In the Philippines, however, there are still a lot of people who smoke cigarettes.',
        choices : {
            a : 'Taboo',
            b : 'Legal',
            c : 'Favorable',
            d : 'Common',
            e : 'Collective'
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : "2.CSC-9", 
        topic: 2.2,
        type : 'M',
        question : 'Unlike dogs which are known to be loyal, cats are _____ in nature.',
        choices : {
            a : 'Treacheous',
            b : 'Dependable',
            c : 'Steadfast',
            d : 'Sweet',
            e : 'Clingy'
        },
        answer : 'a',
        explanation: '',
    },
    {
        no : "2.CSC-10", 
        topic: 2.2,
        type : 'M',
        question : 'The _____ told him to be careul in his way home, for the might encounter a tragedy he will never forget his entire life.',
        choices : {
            a : 'Stranger',
            b : 'Harbinger',
            c : 'Apogee',
            d : 'Dictum',
            e : 'Scintilla'
        },
        answer : 'b',
        explanation: '',
    },
    {
        no : "7.CSC-101", 
        topic: 7,
        type : 'M',
        question : 'The table in the dining room is round. The tbale in the living room is round. The table in the master\'s bedroom is round. So,',
        choices : {
            a : 'The house has so many tables',
            b : 'All the tables are round.',
            c : 'The table in the recreation area is also round.',
            d : 'The chairs are also round.',
        },
        answer : '',
        explanation: '',
    },
    {
        no : "7.CSC-102", 
        topic: 7,
        type : 'M',
        question : 'All players in the Houston Hockey Team weigh more than 200 pounds. John is one of the team\s players. Hence,',
        choices : {
            a : 'John weighs more than 200 pounds',
            b : 'John is the best player',
            c : 'John is a hockey player',
            d : 'John is a good athlete',
        },
        answer : '',
        explanation: '',
    },
    {
        no : "7.CSC-103", 
        topic: 7,
        type : 'M',
        question : 'Every typhoon that falls in the Philippines and nearby countries was created in the Pacific Ocean. Typhoon Senyang destructed the Philippines. Therefore,',
        choices : {
            a : 'Typhoon Senyang also destructed nearby countries',
            b : '',
            c : '',
            d : '',
        },
        answer : '',
        explanation: '',
    },
    // 2.3 Antonyms
        {
            no : "2.3.1",  
            topic: 2.3,
            type : 'M',
            question : 'Czarmaine <b><i>accompanied</b></i> her sister to the drugstore.',
            choices : {
                a : 'followed',
                b : 'let go on one\'s own',
                c : 'left behind',
                d : 'stopped',
            },
            answer : 'b',
            explanation: 'To accompany someone means to go with them. "Let go on one\'s own" is the opposite, which does not match the context, thus "b" is incorrect. The correct answer should be a: followed.',
        },
        {
            no : "2.3.2",  
            topic: 2.3,
            type : 'M',
            question : 'Beside the <b><i>boulevard</b></i> are gigantic buildings.',
            choices : {
                a : 'alley',
                b : 'street',
                c : 'avenue',
                d : 'road',
            },
            answer : 'a',
            explanation: 'A boulevard is a wide street, often lined with trees and buildings. The closest synonym from the choices is "avenue," not "alley." Correct answer should be c: avenue.',
        },
        {
            no : "2.3.3",  
            topic: 2.3,
            type : 'M',
            question : 'He often got into trouble because he was <b><i>brusque</b></i>.',
            choices : {
                a : 'blunt',
                b : 'rude',
                c : 'refined',
                d : 'curt',
            },
            answer : 'c',
            explanation: 'Brusque means abrupt or curt in manner, often perceived as rude. Correct answer should be d: curt.',
        },
        {
            no : "2.3.4",  
            topic: 2.3,
            type : 'M',
            question : 'The reporter\'s <b><i>candid</b></i> remarks caught the mayoralty candidate off-guard.',
            choices : {
                a : 'secret',
                b : 'frank',
                c : 'well-thought',
                d : 'reserved',
            },
            answer : 'c',
            explanation: 'Candid means frank or honest. "Well-thought" does not fit this meaning. Correct answer should be b: frank.',
        },
        {
            no : "2.3.5",  
            topic: 2.3,
            type : 'M',
            question : 'The mean boys <b><i>derided</b></i> the sickly boy.',
            choices : {
                a : 'made fun of',
                b : 'ridiculed',
                c : 'praised',
                d : 'abandoned',
            },
            answer : 'c',
            explanation: 'To deride means to ridicule or mock. Correct answer should be b: ridiculed.',
        },
        {
            no : "2.3.6",  
            topic: 2.3,
            type : 'M',
            question : 'Charm was <b><i>ecstatic</b></i> when she won first prize in the short story writing contest.',
            choices : {
                a : 'melancholic',
                b : 'overjoyed',
                c : 'worried',
                d : 'energetic',
            },
            answer : 'a',
            explanation: 'Ecstatic means extremely happy. Correct answer should be b: overjoyed.',
        },
        {
            no : "2.3.7",  
            topic: 2.3,
            type : 'M',
            question : 'Migraine headaches are <b><i>excruciating</b></i>.',
            choices : {
                a : 'extremely painful',
                b : 'mild pain',
                c : 'painless',
                d : 'healing',
            },
            answer : 'c',
            explanation: 'Excruciating means intensely painful. Correct answer should be a: extremely painful.',
        },
        {
            no : "2.3.8",  
            topic: 2.3,
            type : 'M',
            question : 'The quiz proved to be <b><i>facile</b></i> so the students got high scores.',
            choices : {
                a : 'difficult',
                b : 'easy',
                c : 'average',
                d : 'answerable',
            },
            answer : 'a',
            explanation: 'Facile means easy or simple. Correct answer should be b: easy.',
        },
        {
            no : "2.3.9",  
            topic: 2.3,
            type : 'M',
            question : 'The <b><i>garrulous</b></i> girls were distanced from each other.',
            choices : {
                a : 'mute',
                b : 'talkative',
                c : 'behaved',
                d : 'quiet',
            },
            answer : 'd',
            explanation: 'Garrulous means excessively talkative. Correct answer should be b: talkative.',
        },
        {
            no : "2.3.10",  
            topic: 2.3,
            type : 'M',
            question : 'The <b><i>heathens</b></i> used to practice cannibalism.',
            choices : {
                a : 'uncivilized people',
                b : 'barbaric people',
                c : 'old people',
                d : 'cultured people',
            },
            answer : 'd',
            explanation: 'Heathens refer to people lacking civilized moral principles. Correct answer should be b: barbaric people.',
        },
        {
            no : "2.3.11",  
            topic: 2.3,
            type : 'M',
            question : 'Keep on believing that physical disability is not a <b><i>hindrance</i></b> to success.',
            choices : {
                a : 'block',
                b : 'encouragement',
                c : 'support',
                d : 'help',
            },
            answer : 'a',
            explanation: 'Hindrance means an obstacle or block. The correct synonym is "block".',
        },
        {
            no : "2.3.12",  
            topic: 2.3,
            type : 'M',
            question : 'Never operate a machine once you are <b><i>inebriated</i></b>.',
            choices : {
                a : 'awake',
                b : 'drunk',
                c : 'fit',
                d : 'alert',
            },
            answer : 'b',
            explanation: 'Inebriated means drunk or intoxicated.',
        },
        {
            no : "2.3.13",  
            topic: 2.3,
            type : 'M',
            question : 'The people <b><i>inveighed</i></b> against the sharp increase in oil prices.',
            choices : {
                a : 'voted',
                b : 'talked',
                c : 'protested',
                d : 'whispered',
            },
            answer : 'c',
            explanation: 'Inveighed means protested strongly or spoke against.',
        },
        {
            no : "2.3.14",  
            topic: 2.3,
            type : 'M',
            question : 'Some people believe that breaking a mirror is a <b><i>jinx</i></b>.',
            choices : {
                a : 'bad luck',
                b : 'prayer',
                c : 'ritual',
                d : 'blessing',
            },
            answer : 'a',
            explanation: 'Jinx means a thing that brings bad luck.',
        },
        {
            no : "2.3.15",  
            topic: 2.3,
            type : 'M',
            question : 'The players were confused when the <b><i>kibitzers</i></b> suddenly butted-in during the team\'s huddle.',
            choices : {
                a : 'referees',
                b : 'spectators',
                c : 'players',
                d : 'coaches',
            },
            answer : 'b',
            explanation: 'Kibitzers are onlookers who give unwanted advice or commentary—spectators.',
        },
        {
            no : "2.3.16",  
            topic: 2.3,
            type : 'M',
            question : 'The <b><i>lanky</i></b> lad stood out among the average-sized students.',
            choices : {
                a : 'short and fat',
                b : 'big and bulky',
                c : 'small and shy',
                d : 'tall and thin',
            },
            answer : 'd',
            explanation: 'Lanky means ungracefully thin and tall.',
        },
        {
            no : "2.3.17",  
            topic: 2.3,
            type : 'M',
            question : 'The sickly dog was given a <b><i>lethal</i></b> dose of morphine tablets.',
            choices : {
                a : 'fatal',
                b : 'safe',
                c : 'therapeutic',
                d : 'natural',
            },
            answer : 'a',
            explanation: 'Lethal means deadly or causing death.',
        },
        {
            no : "2.3.18",  
            topic: 2.3,
            type : 'M',
            question : 'Heinous criminals are truly <b><i>loathsome</i></b>.',
            choices : {
                a : 'repugnant',
                b : 'funny',
                c : 'friendly',
                d : 'loyal',
            },
            answer : 'a',
            explanation: 'Loathsome means disgusting or detestable.',
        },
        {
            no : "2.3.19",  
            topic: 2.3,
            type : 'M',
            question : 'We listened attentively to the <b><i>mellifluous</i></b> sound produced by the Philippine Philharmonic Orchestra.',
            choices : {
                a : 'noisy',
                b : 'angry',
                c : 'melodious',
                d : 'silent',
            },
            answer : 'c',
            explanation: 'Mellifluous means sweet-sounding or musical.',
        },
        {
            no : "2.3.20",  
            topic: 2.3,
            type : 'M',
            question : 'The free medical and dental checkup conducted by the AFP Group is just a proof of their <b><i>munificence</i></b>.',
            choices : {
                a : 'poverty',
                b : 'generosity',
                c : 'disinterest',
                d : 'anger',
            },
            answer : 'b',
            explanation: 'Munificence means great generosity or largesse.',
        },
        {
            no : "2.3.21",  
            topic: 2.3,
            type : 'M',
            question : 'The judge was accused of being <b><i>partial</i></b> to the prosecution.',
            choices : {
                a : 'fair',
                b : 'biased',
                c : 'neutral',
                d : 'just',
            },
            answer : 'b',
            explanation: 'Partial means biased or showing favoritism.',
        },
        {
            no : "2.3.22",  
            topic: 2.3,
            type : 'M',
            question : 'Despite the scolding, the student remained <b><i>placid</i></b>.',
            choices : {
                a : 'calm',
                b : 'worried',
                c : 'angry',
                d : 'scared',
            },
            answer : 'a',
            explanation: 'Placid means calm and unbothered.',
        },
        {
            no : "2.3.23",  
            topic: 2.3,
            type : 'M',
            question : 'Her <b><i>plethora</i></b> of clothes made it hard to choose what to wear.',
            choices : {
                a : 'lack',
                b : 'shortage',
                c : 'excess',
                d : 'need',
            },
            answer : 'c',
            explanation: 'Plethora means an excessive amount.',
        },
        {
            no : "2.3.24",  
            topic: 2.3,
            type : 'M',
            question : 'He used <b><i>rhetoric</i></b> to win the audience\'s support.',
            choices : {
                a : 'persuasive speech',
                b : 'lies',
                c : 'jokes',
                d : 'arguments',
            },
            answer : 'a',
            explanation: 'Rhetoric is the art of persuasive speaking or writing.',
        },
        {
            no : "2.3.25",  
            topic: 2.3,
            type : 'M',
            question : 'His <b><i>scrutiny</i></b> of the contract revealed several loopholes.',
            choices : {
                a : 'avoidance',
                b : 'examination',
                c : 'negligence',
                d : 'disinterest',
            },
            answer : 'b',
            explanation: 'Scrutiny means close examination or inspection.',
        },
        {
            no : "2.3.26",  
            topic: 2.3,
            type : 'M',
            question : 'The general remained <b><i>steadfast</i></b> in his command despite criticism.',
            choices : {
                a : 'hesitant',
                b : 'loyal',
                c : 'weak',
                d : 'doubtful',
            },
            answer : 'b',
            explanation: 'Steadfast means firm and unwavering.',
        },
        {
            no : "2.3.27",  
            topic: 2.3,
            type : 'M',
            question : 'The captain gave a <b><i>succinct</i></b> explanation of the mission.',
            choices : {
                a : 'lengthy',
                b : 'confusing',
                c : 'brief',
                d : 'loud',
            },
            answer : 'c',
            explanation: 'Succinct means brief and to the point.',
        },
        {
            no : "2.3.28",  
            topic: 2.3,
            type : 'M',
            question : 'The witness gave a <b><i>tenuous</i></b> alibi that did not hold up in court.',
            choices : {
                a : 'strong',
                b : 'weak',
                c : 'confident',
                d : 'truthful',
            },
            answer : 'b',
            explanation: 'Tenuous means very weak or slight.',
        },
        {
            no : "2.3.29",  
            topic: 2.3,
            type : 'M',
            question : 'The <b><i>venerable</i></b> professor received a standing ovation.',
            choices : {
                a : 'respected',
                b : 'angry',
                c : 'youthful',
                d : 'loud',
            },
            answer : 'a',
            explanation: 'Venerable means accorded a great deal of respect due to age or wisdom.',
        },
        {
            no : "2.3.30",  
            topic: 2.3,
            type : 'M',
            question : 'The <b><i>wily</i></b> thief escaped the police once again.',
            choices : {
                a : 'honest',
                b : 'clumsy',
                c : 'clever',
                d : 'lazy',
            },
            answer : 'c',
            explanation: 'Wily means skilled at gaining an advantage, especially deceitfully.',
        }        
]
/*
    {
        no : "2.3.", 
        topic: 2.3,
        type : 'M',
        question : ' <b><i> </b></i>',
        choices : {
            a : '',
            b : '',
            c : '',
            d : '',
        },
        answer : '',
        explanation: '',
    },
*/

// Function to display questions
