
document.getElementById('subject-title').innerText = 'CIVIL SERVICE PRACTICE EXAM';
document.getElementById('sidebar-subject-title').innerText = 'CIVIL SERVICE PRACTICE EXAM';

const topics = {
    0: 'ALL',
    //1: 'MATHEMATICS',
    1.1: 'MATH - Word Problems', //and Operations',
    //2 : 'VERBAL ABILITY',
    //2.1 : 'Word Meaning',
    2.2: 'Sentence Completion',
    2.3: 'Antonyms',
    //3 : 'FILIPINO',
    4: 'PHILIPPINE CONSTITUTION',
    //5 : 'INDUCTIVE REASONING',
    //6 : 'ABSTRACT REASONING',
    //7 : 'LOGICAL REASONING'
}

const sideBarContainer = document.getElementById("topicLinks"); // The container where links will be inserted

Object.entries(topics).forEach(([key, value]) => {
    const a = document.createElement("a");
    a.href = `../library/practiceExam.html?page=1&subject=cse_question&topic=${key}`;
    a.id = `topic-${key}`;
    a.className = `w3-bar-item w3-button w3-padding `;
    a.innerHTML = `<img src="" class="notepadIcon">${value}`;
    sideBarContainer.appendChild(a);
});


const practiceTest = document.createElement("a");
practiceTest.href = `../library/quiz.html?page=1&subject=cse_question&topic=`;
practiceTest.className = `w3-bar-item w3-button w3-padding topic-quiz`;
practiceTest.innerHTML = `<img src="" class="notepadIcon">PRACTICE QUIZ (FLASHCARD)`;
sideBarContainer.appendChild(practiceTest);



const questions = [
    {
        no: 1,
        topic: 1.1,
        type: 'M',
        question: 'Find the sum: 299 + 943 + 398 + 101.',
        choices: {
            a: '1 531',
            b: '1 641',
            c: '1 741',
            d: '122 222',
        },
        answer: 'c',
        explanation: 'The sum of 299 + 943 + 398 + 101 is <b>1 741</b>',
    },
    {
        no: 2,
        topic: 1.1,
        type: 'M',
        question: 'If 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55, then 11 + 12 + 13 + 14 + 15 + 16 + 17 + 18 + 19 + 20 = ?',
        choices: {
            a: '65',
            b: '155',
            c: '125',
            d: '550',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 3,
        topic: 1.1,
        type: 'M',
        question: 'If 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55, then 101 + 102 + 103 + 104 + 105 + 106 + 107 + 108 + 109 + 110 = ?',
        choices: {
            a: '1 055',
            b: '1 065',
            c: '1 075',
            d: '5 500',
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: 4,
        topic: 1.1,
        type: 'M',
        question: 'Evaluate: {16 - (24 - 8) + 22 x 8 - 8}.',
        choices: {
            a: '40',
            b: '48',
            c: '64',
            d: '168',
        },
        answer: 'd',
        explanation: '',
    },
    {
        no: 5,
        topic: 1.1,
        type: 'M',
        question: 'If 23 + 28 + 37 + x + 53 = 168 and 23 + 28 + 40 + y + 50 = 120. Find the value of x - y?',
        choices: {
            a: '36',
            b: '48',
            c: '56',
            d: '64',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 6,
        topic: 1.1,
        type: 'M',
        question: 'Find the product: 800 x 125',
        choices: {
            a: '925',
            b: '1 000',
            c: '10 000',
            d: '100 000',
        },
        answer: 'd',
        explanation: '',
    },
    {
        no: 7,
        topic: 1.1,
        type: 'M',
        question: 'Find the quotient: 8000 / 125',
        choices: {
            a: '48',
            b: '64',
            c: '80',
            d: '88',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 8,
        topic: 1.1,
        type: 'M',
        question: 'What is the remainder when 192 888 is divided by 8?',
        choices: {
            a: '0',
            b: '4',
            c: '8',
            d: '24 111',
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: 9,
        topic: 1.1,
        type: 'M',
        question: 'Rounding 299 943 to the nearest thousands the result is',
        choices: {
            a: '299 940',
            b: '299 000',
            c: '299 900',
            d: '300 000',
        },
        answer: 'd',
        explanation: '',
    },
    {
        no: 10,
        topic: 1.1,
        type: 'M',
        question: '398.101 is read as',
        choices: {
            a: 'three hundred ninety eight, one hundred one.',
            b: 'three hundred ninety eight and one hundred one.',
            c: 'three hundred ninety eight and one hundred',
            d: 'three hundred ninety eight and one hundred one thousandths',
        },
        answer: 'd',
        explanation: '',
    },
    {
        no: 11,
        topic: 1.1,
        type: 'M',
        question: 'A number is divisible by 8 if its last three digit is divisible by 8. Which of the following numbers is divisible by 8?',
        choices: {
            a: '9 208',
            b: '6 236',
            c: '88 254',
            d: '8 886',
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: 12,
        topic: 1.1,
        type: 'M',
        question: 'A number is divisible by 8 if its last three digit is divisible by 8. Which of the following numbers is divisible by 8?',
        choices: {
            a: '9 208',
            b: '6 236',
            c: '88 254',
            d: '8 886',
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: 18,
        topic: 1.1,
        type: 'M',
        question: 'What is 25% of 228',
        choices: {
            a: '52',
            b: '57',
            c: '54',
            d: '912',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 21,
        topic: 1.1,
        type: 'M',
        question: 'Evaluate: 123 x 0.1 + 123 x 0.01 + 123 x 0.001',
        choices: {
            a: '13.653',
            b: '135.53',
            c: '1356.3',
            d: '13563',
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: 24,
        topic: 1.1,
        type: 'M',
        question: 'Find the value of x in the equation 3x + 7 = 28',
        choices: {
            a: '7',
            b: '-7',
            c: '+-7',
            d: '4',
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: 26,
        topic: 1.1,
        type: 'M',
        question: 'Which of the following <b><i>cannot</b><i> yield an odd integer when divided by 10?',
        choices: {
            a: 'The sum of two odd integers',
            b: 'The product of a prime number and an odd integer',
            c: 'The product of two odd integers',
            d: 'The sum of three consecutive integers',
        },
        answer: 'c',
        explanation: '',
    },
    {
        no: 27,
        topic: 1.1,
        type: 'M',
        question: 'If 8x + 12 = 24, what is the value of 24x + 36?',
        choices: {
            a: '4',
            b: '6',
            c: '8',
            d: '72',
        },
        answer: 'd',
        explanation: '',
    },
    {
        no: 28,
        topic: 1.1,
        type: 'M',
        question: 'If a positive integer <b><i>m</b></i> is divisible by both 3 and 8, then <b><i>m</b></i> must also be divisible by?',
        choices: {
            a: '10',
            b: '18',
            c: '24',
            d: '60',
        },
        answer: 'c',
        explanation: '',
    },
    {
        no: 29,
        topic: 1.1,
        type: 'M',
        question: 'If positive integers <b><i>m</b></i> and <b><i>n</b></i> are not both odd, which of the following is always true?',
        choices: {
            a: 'm + n is even',
            b: 'mn is even',
            c: 'm - n cannot be odd',
            d: 'm + n - 1 is odd',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 30,
        topic: 1.1,
        type: 'M',
        question: 'Find the average temperature change for the 12-day period. Temperature change in degree celsius: 2.6, 3.8, 7.0, 4.5, 4.6, 7.9, 5.0, 8.1, 4.4, 5.3, 6.4, 5.2.',
        choices: {
            a: '4.8',
            b: '4.9',
            c: '5.2',
            d: '5.4',
        },
        answer: 'd',
        explanation: '',
    },
    {
        no: 4.1,
        topic: 4,
        type: 'M',
        question: 'What is the highest law of the land in the Philippines',
        choices: {
            a: 'Civil Code',
            b: 'Philippine Constitution',
            c: 'Penal Code',
            d: 'Local Government Code',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 4.2,
        topic: 4,
        type: 'M',
        question: 'How many articles are there in the 1987 Philippine Constitution?',
        choices: {
            a: '18',
            b: '12',
            c: '21',
            d: '22',
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: 4.3,
        topic: 4,
        type: 'M',
        question: 'Which branch of the government is responsible for making laws?',
        choices: {
            a: 'Executive',
            b: 'Legislative',
            c: 'Judicial',
            d: 'Electoral',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 4.4,
        topic: 4,
        type: 'M',
        question: 'The power to declare martial law is vested in which official?',
        choices: {
            a: 'Senate President',
            b: 'Chief Justice',
            c: 'President of the Philippines',
            d: 'Speaker of the House',
        },
        answer: 'c',
        explanation: '',
    },
    {
        no: 4.5,
        topic: 4,
        type: 'M',
        question: 'Which article of the Constitution focuses on the Bill of Rights',
        choices: {
            a: 'Article II',
            b: 'Article III',
            c: 'Article IV',
            d: 'Article V',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 4.6,
        topic: 4,
        type: 'M',
        question: 'Who is responsible for determining the existence of probable cause for the issuance of a warrant of arrest or search warrant?',
        choices: {
            a: 'Lawyer',
            b: 'Judge',
            c: 'Fiscal',
            d: 'Prosecutor',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 4.7,
        topic: 4,
        type: 'M',
        question: 'The Senate shall be composed of how many senators elected at large by voters of the Philippines?',
        choices: {
            a: '21',
            b: '22',
            c: '23',
            d: '24',
        },
        answer: 'd',
        explanation: '',
    },
    {
        no: 4.8,
        topic: 4,
        type: 'M',
        question: 'The term of office of the President and Vice-President of the Philippines shall be up to how many years?',
        choices: {
            a: '3 Years',
            b: '4 Years',
            c: '5 Years',
            d: '6 Years',
        },
        answer: 'd',
        explanation: '',
    },
    {
        no: 4.9,
        topic: 4,
        type: 'M',
        question: 'It states that "no person shall be deprived of life, liberty, or property without due process of law, nor any person be denied the equal protection of the laws.',
        choices: {
            a: 'Article VI',
            b: 'Bill of Rights',
            c: 'Republic Act',
            d: 'Court Order',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: 4.10,
        topic: 4,
        type: 'M',
        question: 'What are the 3 branches of the Governemnt of the Philippines?',
        choices: {
            a: 'Senate, Supreme Court, Congress',
            b: 'Presidential, Unicameral - Parliamentary, Bicameral -Parliamentary',
            c: 'Legislative, Executive, Judicial',
            d: 'The Legislative, The Senate, The Supreme Court',
        },
        answer: 'c',
        explanation: '',
    },
    {
        no: 4.11,
        topic: 4,
        type: 'M',
        question: 'The following shall be exempted from taxation except:',
        choices: {
            a: 'Lands and buildings',
            b: 'Churches and convents',
            c: 'Charitable institutions',
            d: 'Non-profit cemeteries',
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: 4.12,
        topic: 4,
        type: 'M',
        question: 'It is a law in the Philippines that aims to address legal issues concerning online interactions and harmful internet behavior in the Philippines. It aims to present and punish cybercrime in the country.',
        choices: {
            a: 'Cybersquatting',
            b: 'Cybercrime Act',
            c: 'Cybercrime Prevention Act',
            d: 'Cyber Identity Theft Act',
        },
        answer: 'c',
        explanation: '',
    },
    {
        no: 4.13,
        topic: 4,
        type: 'M',
        question: 'It is a project of DOST for more accurate integrated and responsive disaster prevention and mitigation system expecially in high-risk calamity areas of the Philippines',
        choices: {
            a: 'PAGASA',
            b: 'I am ready',
            c: 'DOST - Advance Disaster Program',
            d: 'Project NOAH',
        },
        answer: 'd',
        explanation: 'D. Project NOAH - Nationwide Operational Assessment of Hazards',
    },
    {
        no: 4.14,
        topic: 4,
        type: 'M',
        question: 'The member of the House of Representatives shall be elected for a term of _____.',
        choices: {
            a: '3 Years',
            b: '4 Years',
            c: '5 Years',
            d: '6 Years',
        },
        answer: 'a',
        explanation: 'A. 3 Years is the term of the Elecetd Represenative and also the Senator',
    },
    {
        no: 4.15,
        topic: 4,
        type: 'M',
        question: 'It is the power of the State to promote public welfare by restraining the use of both liberty and property of all people',
        choices: {
            a: 'Police Power',
            b: 'Power of Eminent Domain',
            c: 'Power of Taxation',
            d: 'Power to Impeach',
        },
        answer: 'a',
        explanation: 'A. Police Power',
    },
    {
        no: "4.2025edCSC-2",
        topic: 4,
        type: 'M',
        question: 'The legislative power shall be vested in the ______ which shall consist of a Senate and a House of Representative',
        choices: {
            a: 'Congress of the Philippines',
            b: 'House of Ombudsman',
            c: 'The Supreme Court',
            d: 'Bureau of Internal Revenue',
        },
        answer: 'a',
        explanation: 'Legislative power is vested in the Congress of the Philippines, composed of the Senate and the House of Representatives, as stated in Article VI, Section 1 of the 1987 Philippine Constitution.',
    },
    {
        no: "4.2025edCSC-3",
        topic: 4,
        type: 'M',
        question: 'Who is the current Senate President of the Philippines?',
        choices: {
            a: 'Vicente Castelo Sotto III',
            b: 'Juan Miguel "Migz" Fernandex Zubiri',
            c: 'Francis Joseph "Chiz" Guevara Escudero',
            d: 'Frankin Magtanao Drilon',
        },
        answer: 'c',
        explanation: 'As of 2025, the current Senate President of the Philippines is Francis "Chiz" Escudero, elected to the position in 2024.',
    },
    {
        no: "4.2025edCSC-4",
        topic: 4,
        type: 'M',
        question: 'Who is the current Speaker of the House of Representative in the Philippines?',
        choices: {
            a: 'Elizaldy S. Co',
            b: 'Ferdinand Martin G. Romualdez',
            c: 'Stella Luz A. Quimbo',
            d: 'Gloria Macapagal-Arroyo',
        },
        answer: 'b',
        explanation: 'Ferdinand Martin G. Romualdez continues to serve as the Speaker of the House of Representatives as of 2025, a position he held since 2022.',
    },
    {
        no: "4.2025edCSC-5",
        topic: 4,
        type: 'M',
        question: 'Who is the current Chairperson of the House Committee on Appropriations?',
        choices: {
            a: 'Elizaldy "Zaldy" S. Co',
            b: 'Manuel Jose "Mannix" Dalipe',
            c: 'Stella Luiz A. Quimbo',
            d: 'Ferdinand Martin G. Romualdez',
        },
        answer: 'c',
        explanation: 'Stella Luiz A. Quimbo is the current Chairperson of the House Committee on Appropriations, responsible for handling budget-related legislation in the House.',
    },
    {
        no: "4.2025edCSC-6",
        topic: 4,
        type: 'M',
        question: 'The executive power shall be vested in the ____.',
        choices: {
            a: 'President of the Philippines',
            b: 'House of Representatives',
            c: 'The Supreme Court',
            d: 'The Congress',
        },
        answer: 'a',
        explanation: 'According to Article VII, Section 1 of the 1987 Philippine Constitution, the executive power is vested in the President of the Philippines, who acts as the head of state and government.',
    },
    {
        no: "2.R",
        topic: 2.2,
        type: 'M',
        question: 'The researcher’s groundbreaking work was met with initial resistance, but over time, it gained widespread _______ as further studies confirmed its validity.',
        choices: {
            a: 'Disapproval',
            b: 'Recognition',
            c: 'Indifference',
            d: 'Opposition',
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: "2.R",
        topic: 2.2,
        type: 'M',
        question: 'The engineers said the bridge was now ______, however, no one wanted to risk crossing it.',
        choices: {
            a: 'protected',
            b: 'prudent',
            c: 'fixed',
            d: 'safe',
        },
        answer: 'c',
        explanation: 'The structure of the sentence gives us a clue. It has two contrasting parts, connected by "however," which signals a contradiction. This means that although the engineers claimed something positive, people still did not trust the bridge enough to cross it. So, "fixed" makes the most sense because it acknowledges that the bridge was repaired, but people were still unsure or scared to cross—which matches the contrast introduced by “however.”',
    },
    {
        no: "2.CSC-1",
        topic: 2.2,
        type: 'M',
        question: 'The commoners played a show about the Lannisters, a _____ of the ineffective rulling of the leaders of King\'s Landing.',
        choices: {
            a: 'Play',
            b: 'Travesty',
            c: 'Pretention',
            d: 'Role-Playing',
            e: 'Showcase'
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: "2.CSC-2",
        topic: 2.2,
        type: 'M',
        question: 'The dentist ridiculed his patient\' ____ tooth enamel.',
        choices: {
            a: 'hard',
            b: 'favorable',
            c: 'healthy',
            d: 'mottled',
            e: 'lovely'
        },
        answer: 'd',
        explanation: '',
    },
    {
        no: "2.R",
        topic: 2.2,
        type: 'M',
        question: 'To ensure that Nathalie wouldn\'t know where we were going for her birthday, I took the most _____ route i could think of.',
        choices: {
            a: 'circuitous',
            b: 'craven',
            c: 'enigmatic',
            d: 'mercurial',
        },
        answer: 'a',
        explanation: 'The best word to complete the sentence is a. circuitous.',
    },
    {
        no: "2.CSC-3",
        topic: 2.2,
        type: 'M',
        question: 'Arya _____ upon witnessing his father\'s decapitation. Her face because ashen upon seeing such horabble scene, and she was not able to say anuthing for a while.',
        choices: {
            a: 'Gasped',
            b: 'Looked',
            c: 'Flummoxed',
            d: 'Breathed',
            e: 'Flunked'
        },
        answer: 'c',
        explanation: '',
    },
    {
        no: "2.CSC-4",
        topic: 2.2,
        type: 'M',
        question: 'Emma Watson was chosen to become a/an _____ for the remake of Beauty and the Beast in 2017. She will be playing as Belle.',
        choices: {
            a: 'Antagonist',
            b: 'Protagonist',
            c: 'Wicked',
            d: 'Opponent',
            e: 'Narrator'
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: "2.CSC-5",
        topic: 2.2,
        type: 'M',
        question: 'The beast promised to _____ havoc if ever somebody trespasses his kingdom.',
        choices: {
            a: 'Endow',
            b: 'Warrant',
            c: 'Ensue',
            d: 'Placate',
            e: 'Wreak'
        },
        answer: 'e',
        explanation: '',
    },
    {
        no: "2.CSC-6",
        topic: 2.2,
        type: 'M',
        question: 'Mae\'s talent in singing _____ under the tutelage of Prof. Dela Cruz, her music teacher. She is now a well-known singer from across the world.',
        choices: {
            a: 'Improved',
            b: 'Flourished',
            c: 'Embellished',
            d: 'Colluded',
            e: 'touted'
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: "2.CSC-7",
        topic: 2.2,
        type: 'M',
        question: 'Ana reached the _____ of her career upon the release of her second novel, which gained positive remarks from world-renowned authors from different countries.',
        choices: {
            a: 'Apogee',
            b: 'Plateau',
            c: 'Bottom',
            d: 'Trough',
            e: 'Downfall'
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: "2.CSC-8",
        topic: 2.2,
        type: 'M',
        question: 'Smoking cigarettes is mostly _____ in some part of the world. In the Philippines, however, there are still a lot of people who smoke cigarettes.',
        choices: {
            a: 'Taboo',
            b: 'Legal',
            c: 'Favorable',
            d: 'Common',
            e: 'Collective'
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: "2.CSC-9",
        topic: 2.2,
        type: 'M',
        question: 'Unlike dogs which are known to be loyal, cats are _____ in nature.',
        choices: {
            a: 'Treacheous',
            b: 'Dependable',
            c: 'Steadfast',
            d: 'Sweet',
            e: 'Clingy'
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: "2.CSC-10",
        topic: 2.2,
        type: 'M',
        question: 'The _____ told him to be careul in his way home, for the might encounter a tragedy he will never forget his entire life.',
        choices: {
            a: 'Stranger',
            b: 'Harbinger',
            c: 'Apogee',
            d: 'Dictum',
            e: 'Scintilla'
        },
        answer: 'b',
        explanation: '',
    },
    {
        no: "2.Scrib-24",
        topic: 2.2,
        type: 'M',
        question: 'The air was bitter cold, the temperature well below the freezing point, yet they found themselves _____ freely as they clambered up the steep northen slope.',
        choices: {
            a: 'Laughing',
            b: 'Perspiring',
            c: 'Disporting',
            d: 'Shivering',
            e: 'Confiding'
        },
        answer: 'b',
        explanation: '',
    },    
    {
        no: "2.Scrib-19",
        topic: 2.2,
        type: 'M',
        question: 'We are taking aback when we learned of his defection, never having suspected that he was anything but loyal, so credible has been his ____ of fidelity and devotion to the cause.',
        choices: {
            a: 'Vociferation',
            b: 'Intimidation',
            c: 'Dissimulation',
            d: 'Presumption',
            e: 'Presentiment'
        },
        answer: 'a',
        explanation: '',
    },
    {
        no: "7.CSC-101",
        topic: 7,
        type: 'M',
        question: 'The table in the dining room is round. The tbale in the living room is round. The table in the master\'s bedroom is round. So,',
        choices: {
            a: 'The house has so many tables',
            b: 'All the tables are round.',
            c: 'The table in the recreation area is also round.',
            d: 'The chairs are also round.',
        },
        answer: '',
        explanation: '',
    },
    {
        no: "7.CSC-102",
        topic: 7,
        type: 'M',
        question: 'All players in the Houston Hockey Team weigh more than 200 pounds. John is one of the team\s players. Hence,',
        choices: {
            a: 'John weighs more than 200 pounds',
            b: 'John is the best player',
            c: 'John is a hockey player',
            d: 'John is a good athlete',
        },
        answer: '',
        explanation: '',
    },
    {
        no: "7.CSC-103",
        topic: 7,
        type: 'M',
        question: 'Every typhoon that falls in the Philippines and nearby countries was created in the Pacific Ocean. Typhoon Senyang destructed the Philippines. Therefore,',
        choices: {
            a: 'Typhoon Senyang also destructed nearby countries',
            b: '',
            c: '',
            d: '',
        },
        answer: '',
        explanation: '',
    },
    // 2.3 Antonyms
    {
        no: "2.3.1",
        topic: 2.3,
        type: 'M',
        question: 'Czarmaine <b><i>accompanied</b></i> her sister to the drugstore.',
        choices: {
            a: 'followed',
            b: 'let go on one\'s own',
            c: 'left behind',
            d: 'stopped',
        },
        answer: 'b',
        explanation: 'To accompany someone means to go with them. "Let go on one\'s own" is the opposite, which does not match the context, thus "b" is incorrect. The correct answer should be a: followed.',
    },
    {
        no: "2.3.2",
        topic: 2.3,
        type: 'M',
        question: 'Beside the <b><i>boulevard</b></i> are gigantic buildings.',
        choices: {
            a: 'alley',
            b: 'street',
            c: 'avenue',
            d: 'road',
        },
        answer: 'a',
        explanation: 'A boulevard is a wide street, often lined with trees and buildings. The closest synonym from the choices is "avenue," not "alley." Correct answer should be c: avenue.',
    },
    {
        no: "2.3.3",
        topic: 2.3,
        type: 'M',
        question: 'He often got into trouble because he was <b><i>brusque</b></i>.',
        choices: {
            a: 'blunt',
            b: 'rude',
            c: 'refined',
            d: 'curt',
        },
        answer: 'c',
        explanation: 'Brusque means abrupt or curt in manner, often perceived as rude. Correct answer should be d: curt.',
    },
    {
        no: "2.3.4",
        topic: 2.3,
        type: 'M',
        question: 'The reporter\'s <b><i>candid</b></i> remarks caught the mayoralty candidate off-guard.',
        choices: {
            a: 'secret',
            b: 'frank',
            c: 'well-thought',
            d: 'reserved',
        },
        answer: 'c',
        explanation: 'Candid means frank or honest. "Well-thought" does not fit this meaning. Correct answer should be b: frank.',
    },
    {
        no: "2.3.5",
        topic: 2.3,
        type: 'M',
        question: 'The mean boys <b><i>derided</b></i> the sickly boy.',
        choices: {
            a: 'made fun of',
            b: 'ridiculed',
            c: 'praised',
            d: 'abandoned',
        },
        answer: 'c',
        explanation: 'To deride means to ridicule or mock. Correct answer should be b: ridiculed.',
    },
    {
        no: "2.3.6",
        topic: 2.3,
        type: 'M',
        question: 'Charm was <b><i>ecstatic</b></i> when she won first prize in the short story writing contest.',
        choices: {
            a: 'melancholic',
            b: 'overjoyed',
            c: 'worried',
            d: 'energetic',
        },
        answer: 'a',
        explanation: 'Ecstatic means extremely happy. Its antonym is melancholic, which means very sad.',
    },
    {
        no: "2.3.7",
        topic: 2.3,
        type: 'M',
        question: 'Migraine headaches are <b><i>excruciating</b></i>.',
        choices: {
            a: 'extremely painful',
            b: 'mild pain',
            c: 'painless',
            d: 'healing',
        },
        answer: 'c',
        explanation: 'Excruciating means intensely painful. Its antonym is painless.',
    },
    {
        no: "2.3.8",
        topic: 2.3,
        type: 'M',
        question: 'The quiz proved to be <b><i>facile</b></i> so the students got high scores.',
        choices: {
            a: 'difficult',
            b: 'easy',
            c: 'average',
            d: 'answerable',
        },
        answer: 'a',
        explanation: 'Facile means easy or simple. Its antonym is difficult.',
    },
    {
        no: "2.3.9",
        topic: 2.3,
        type: 'M',
        question: 'The <b><i>garrulous</b></i> girls were distanced from each other.',
        choices: {
            a: 'mute',
            b: 'talkative',
            c: 'behaved',
            d: 'quiet',
        },
        answer: 'd',
        explanation: 'Garrulous means excessively talkative. Its antonym is quiet.',
    },
    {
        no: "2.3.10",
        topic: 2.3,
        type: 'M',
        question: 'The <b><i>heathens</b></i> used to practice cannibalism.',
        choices: {
            a: 'uncivilized people',
            b: 'barbaric people',
            c: 'old people',
            d: 'cultured people',
        },
        answer: 'd',
        explanation: 'Heathens refer to uncultured or irreligious people. The antonym is cultured people.',
    },
    {
        no: "2.3.25",
        topic: 2.3,
        type: 'M',
        question: 'I admire people who are modest despite their <b><i>opulence</i></b>.',
        choices: {
            a: 'Great wealth',
            b: 'Poverty',
            c: 'Affluence',
            d: 'Lavishes',
        },
        answer: 'b',
        explanation: '"Opulence" means great wealth or luxuriousness. The antonym is "poverty."',
    },
    {
        no: "2.3.12",
        topic: 2.3,
        type: 'M',
        question: 'Never operate a machine once you are <b><i>inebriated</i></b>.',
        choices: {
            a: 'Sober',
            b: 'Drunk',
            c: 'Sleepy',
            d: 'Active',
        },
        answer: 'a',
        explanation: '"Inebriated" means drunk or intoxicated. The antonym is "sober," which means not affected by alcohol.',
    },
    {
        no: "2.3.36",
        topic: 2.3,
        type: 'M',
        question: 'If words were swords, then her <b><i>vitriolic</i></b> remarks could really kill.',
        choices: {
            a: 'Scathing',
            b: 'Sarcastic',
            c: 'Satirical',
            d: 'Kind',
        },
        answer: 'd',
        explanation: '"Vitriolic" means filled with bitter criticism. The antonym is "kind."',
    },
    {
        no: "2.3.22",
        topic: 2.3,
        type: 'M',
        question: 'The CSE Practice Exam Books are <b><i>noteworthy</i></b> materials.',
        choices: {
            a: 'Remarkable',
            b: 'Substantial',
            c: 'Trivial',
            d: 'Significant',
        },
        answer: 'c',
        explanation: '"Noteworthy" means deserving attention; significant. The antonym is "trivial."',
    },
    {
        no: "2.3.19",
        topic: 2.3,
        type: 'M',
        question: 'We listened attentively to the <b><i>mellifluous</i></b> sound produced by the Philippine Philharmonic Orchestra.',
        choices: {
            a: 'Harsh',
            b: 'Resonant',
            c: 'Melodious',
            d: 'Mellow',
        },
        answer: 'a',
        explanation: '"Mellifluous" means sweet or musical; pleasant to hear. The antonym is "harsh."',
    },
    {
        no: "2.3.32",
        topic: 2.3,
        type: 'M',
        question: 'CJ de Silva’s painting abilities are <b><i>uncanny</i></b>.',
        choices: {
            a: 'Remarkable',
            b: 'Ordinary',
            c: 'Astonishing',
            d: 'Unbelievable',
        },
        answer: 'b',
        explanation: '"Uncanny" means strange or remarkable. The antonym is "ordinary."',
    },
    {
        no: "2.3.23",
        topic: 2.3,
        type: 'M',
        question: 'You will never get sufficient nourishment if you are <b><i>obdurate</i></b> in refusing to eat vegetables.',
        choices: {
            a: 'Stubborn',
            b: 'Obedient',
            c: 'Firm',
            d: 'Willful',
        },
        answer: 'b',
        explanation: '"Obdurate" means stubborn or unyielding. The antonym is "obedient."',
    },
    {
        no: "2.3.13",
        topic: 2.3,
        type: 'M',
        question: 'The people <b><i>inveighed</i></b> against the sharp increase in oil prices.',
        choices: {
            a: 'Admitted',
            b: 'Amended',
            c: 'Accepted',
            d: 'Deliberated',
        },
        answer: 'c',
        explanation: '"Inveighed" means to protest strongly or speak out against something. The antonym is "accepted," which means to receive or agree to something willingly.',
    },
    {
        no: "2.3.28",
        topic: 2.3,
        type: 'M',
        question: 'Chin is such a <b><i>precocious</i></b> girl who can already read at age three.',
        choices: {
            a: 'Slow learner',
            b: 'Bright',
            c: 'Inquisitive',
            d: 'Advanced',
        },
        answer: 'a',
        explanation: '"Precocious" means advanced for one\'s age. The antonym is "slow learner."',
    },
    {
        no: "2.3.26",
        topic: 2.3,
        type: 'M',
        question: 'Do you always try to be a <b><i>paragon</i></b> of virtue?',
        choices: {
            a: 'Model',
            b: 'Example',
            c: 'Yardstick',
            d: 'Anomaly',
        },
        answer: 'd',
        explanation: '"Paragon" means a model of excellence. The antonym is "anomaly," which means something that deviates from the norm.',
    },
    {
        no: "2.3.21",
        topic: 2.3,
        type: 'M',
        question: 'Justice calls for penalizing <b><i>nefarious</i></b> acts.',
        choices: {
            a: 'Honorable',
            b: 'Detestable',
            c: 'Infamous',
            d: 'Vile',
        },
        answer: 'a',
        explanation: '"Nefarious" means wicked or criminal. The antonym is "honorable."',
    },
    {
        no: "2.3.11",
        topic: 2.3,
        type: 'M',
        question: 'Keep on believing that physical disability is not a <b><i>hindrance</i></b> to success.',
        choices: {
            a: 'Block',
            b: 'Stepping stone',
            c: 'Opportunity',
            d: 'Difficulty',
        },
        answer: 'b',
        explanation: 'A "hindrance" is something that impedes or blocks progress, while a "stepping stone" is something that helps you move forward. Thus, "stepping stone" is the antonym.',
    },
    {
        no: "2.3.14",
        topic: 2.3,
        type: 'M',
        question: 'Some people believe that breaking a mirror is a <b><i>jinx</i></b>.',
        choices: {
            a: 'Bad luck',
            b: 'Evil',
            c: 'Expensive',
            d: 'Good luck',
        },
        answer: 'd',
        explanation: 'A "jinx" is something that brings bad luck. The antonym is "good luck."',
    },
    {
        no: "2.3.16",
        topic: 2.3,
        type: 'M',
        question: 'The <b><i>lanky</i></b> lad stood out among the average-sized students.',
        choices: {
            a: 'Fierce-looking',
            b: 'Gigantic',
            c: 'Short and stout',
            d: 'Tall and thin',
        },
        answer: 'c',
        explanation: '"Lanky" means tall and thin. The antonym is "short and stout."',
    },
    {
        no: "2.3.18",
        topic: 2.3,
        type: 'M',
        question: '<b><i>Heinous</i></b> criminals are truly loathsome.',
        choices: {
            a: 'Repugnant',
            b: 'Foul',
            c: 'Adorable',
            d: 'Nasty',
        },
        answer: 'c',
        explanation: '"Heinous" means extremely wicked or evil. The antonym is "adorable," which means lovable or delightful.',
    },
    {
        no: "2.3.20",
        topic: 2.3,
        type: 'M',
        question: 'The free medical and dental checkup conducted by the AFP Group is just a proof of their <b><i>munificence</i></b>.',
        choices: {
            a: 'Commitment',
            b: 'Generosity',
            c: 'Extravagance',
            d: 'Stinginess',
        },
        answer: 'd',
        explanation: '"Munificence" means great generosity. The antonym is "stinginess."',
    },
    {
        no: "2.3.31",
        topic: 2.3,
        type: 'M',
        question: 'An A-rating represents the <b><i>ultimate</i></b> honor a film will ever have.',
        choices: {
            a: 'Greatest',
            b: 'Pinnacle',
            c: 'Least',
            d: 'Supreme',
        },
        answer: 'c',
        explanation: '"Ultimate" means the best or most extreme. The antonym is "least."',
    },
    {
        no: "2.3.34",
        topic: 2.3,
        type: 'M',
        question: 'The strong current of the floodwaters caused the wooden bridge to <b><i>vacillate</i></b>.',
        choices: {
            a: 'Collapse',
            b: 'Sway',
            c: 'Vibrate',
            d: 'Be firm',
        },
        answer: 'd',
        explanation: '"Vacillate" means to waver or be indecisive. The antonym is "be firm."',
    },
    {
        no: "2.3.27",
        topic: 2.3,
        type: 'M',
        question: 'Tragic stories had so much <b><i>pathos</i></b> that it left me feeling down.',
        choices: {
            a: 'Anguish',
            b: 'Woe',
            c: 'Intrigue',
            d: 'Humor',
        },
        answer: 'd',
        explanation: '"Pathos" means a quality that evokes pity or sadness. The antonym is "humor."',
    },
    {
        no: "2.3.29",
        topic: 2.3,
        type: 'M',
        question: 'She had the <b><i>quixotic</i></b> idea that she was a reincarnation of a British princess.',
        choices: {
            a: 'Wild',
            b: 'Fantastic',
            c: 'Realistic',
            d: 'Dreamy',
        },
        answer: 'c',
        explanation: '"Quixotic" means exceedingly idealistic or unrealistic. The antonym is "realistic."',
    },
    {
        no: "2.3.24",
        topic: 2.3,
        type: 'M',
        question: 'Don’t be so <b><i>obtrusive</i></b> but instead, mind your own business.',
        choices: {
            a: 'Reserved',
            b: 'Snoopy',
            c: 'Nosey',
            d: 'Interfering',
        },
        answer: 'a',
        explanation: '"Obtrusive" means noticeable or prominent in an unwelcome way. The antonym is "reserved."',
    },
    {
        no: "2.3.33",
        topic: 2.3,
        type: 'M',
        question: 'Lea Salonga’s performance was <b><i>utterly</i></b> delightful.',
        choices: {
            a: 'Somewhat',
            b: 'Entirely',
            c: 'Thoroughly',
            d: 'Absolutely',
        },
        answer: 'a',
        explanation: '"Utterly" means completely or absolutely. The antonym is "somewhat."',
    },
    {
        no: "2.3.39",
        topic: 2.3,
        type: 'M',
        question: 'The tutors are all <b><i>zealous</i></b> tutors who nourish eager minds.',
        choices: {
            a: 'Vigorous',
            b: 'Earnest',
            c: 'Indifferent',
            d: 'Enthusiastic',
        },
        answer: 'c',
        explanation: '"Zealous" means showing great energy or enthusiasm. The antonym is "indifferent."',
    },
    {
        no: "2.3.30",
        topic: 2.3,
        type: 'M',
        question: 'The <b><i>ramshackle</i></b> building collapsed easily.',
        choices: {
            a: 'New',
            b: 'Old',
            c: 'Outdated',
            d: 'Shabby',
        },
        answer: 'a',
        explanation: '"Ramshackle" means in a state of severe disrepair. The antonym is "new."',
    },
    {
        no: "2.3.35",
        topic: 2.3,
        type: 'M',
        question: 'The <b><i>vindictive</i></b> politician spread rumors about his opponent.',
        choices: {
            a: 'Revengeful',
            b: 'Forgiving',
            c: 'Spiteful',
            d: 'Malicious',
        },
        answer: 'b',
        explanation: '"Vindictive" means having a strong desire for revenge. The antonym is "forgiving."',
    },
    {
        no: "2.3.40",
        topic: 2.3,
        type: 'M',
        question: 'Don’t let <b><i>trivial</i></b> things upset you.',
        choices: {
            a: 'Important',
            b: 'Trifling',
            c: 'Ordinary',
            d: 'Inconsequential',
        },
        answer: 'a',
        explanation: '"Trivial" means of little value or importance. The antonym is "important."',
    },
    {
        no: "2.3.37",
        topic: 2.3,
        type: 'M',
        question: 'Many students <b><i>vouch</i></b> for the effectiveness of the review classes.',
        choices: {
            a: 'Guarantee',
            b: 'Endorse',
            c: 'Affirm',
            d: 'Refute',
        },
        answer: 'd',
        explanation: '"Vouch" means to confirm or support as true. The antonym is "refute."',
    },
    {
        no: "2.3.38",
        topic: 2.3,
        type: 'M',
        question: 'The <b><i>yonder</i></b> youth is more studious than the nearer one.',
        choices: {
            a: 'Lonesome',
            b: 'Farther',
            c: 'Closer',
            d: 'Thither',
        },
        answer: 'c',
        explanation: '"Yonder" means at some distance in the direction indicated. The antonym is "closer."',
    },
    {
        no: "2.3.17",
        topic: 2.3,
        type: 'M',
        question: 'The sickly dog was given a <b><i>lethal</i></b> dose of morphine tablets.',
        choices: {
            a: 'Fatal',
            b: 'Safe',
            c: 'Deadly',
            d: 'Nasty',
        },
        answer: 'b',
        explanation: '"Lethal" means deadly or fatal. The antonym is "safe."',
    },
    {
        no: "2.3.15",
        topic: 2.3,
        type: 'M',
        question: 'The players were confused when the <b><i>kibitzers</i></b> suddenly butted-in during the team’s huddle.',
        choices: {
            a: 'Advisers',
            b: 'Spectators',
            c: 'Onlookers',
            d: 'Crowd',
        },
        answer: 'a',
        explanation: '"Kibitzers" are people who offer unwanted advice or commentary. The antonym is "advisers," who are expected to give advice and are usually welcomed.',
    },
];
/*
    {
        no : "2.3.", 
        topic: 2.3,
        type : 'M',
        question : ' <b><i> </b></i>',
        choices : {
            a : '',
            b : '',
            c : '',
            d : '',
        },
        answer : '',
        explanation: '',
    },
*/

// Function to display questions

  const topicName = 'CIVIL SERVICE EXAM REVIEWER 2025';

const fileName = window.location.pathname.split("/").pop();
if (fileName === 'quiz.html') {
    const script = document.createElement('script');
    script.src = '../asset/js/newPracticeQuiz.js';
    document.head.appendChild(script);
} else if (fileName == 'practiceExam.html') {
    const script = document.createElement('script');
    script.src = '../asset/js/quiz.js';
    document.head.appendChild(script);
} else {
    const script = document.createElement('script');
    script.src = '../asset/js/quizAdmin.js';
    document.head.appendChild(script);
}

